version: "3.8"

services:
  nodo1:
    image: cockroachdb/cockroach:latest
    container_name: nodo1
    hostname: nodo1 # Importante para el DNS interno
    ports:
      - "26257:26257" # SQL (externo:26257 → interno:26257)
      - "8080:8080" # UI
    volumes:
      - nodo1:/cockroach/cockroach-data
    command: start-single-node --insecure --advertise-addr=nodo1

  nodo2:
    image: cockroachdb/cockroach:latest
    container_name: nodo2
    hostname: nodo2
    ports:
      - "26258:26257" # SQL (externo:26258 → interno:26257)
      - "8081:8080" # UI
    volumes:
      - nodo2:/cockroach/cockroach-data
    command: start --insecure --store=node2 --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080 --join=nodo1:26257 --advertise-addr=nodo2

  nodo3:
    image: cockroachdb/cockroach:latest
    container_name: nodo3
    hostname: nodo3
    ports:
      - "26259:26257" # SQL (externo:26259 → interno:26257)
      - "8082:8080" # UI
    volumes:
      - nodo3:/cockroach/cockroach-data
    command: start --insecure --store=node3 --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080 --join=nodo1:26257 --advertise-addr=nodo3

  nodo4:
    image: cockroachdb/cockroach:latest
    container_name: nodo4
    hostname: nodo4
    ports:
      - "26256:26257" # SQL (externo:26256 → interno:26257)
      - "8083:8080" # UI
    volumes:
      - nodo4:/cockroach/cockroach-data
    command: start --insecure --store=node4 --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080 --join=nodo1:26257 --advertise-addr=nodo4

volumes:
  nodo1:
  nodo2:
  nodo3:
  nodo4:
